language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

services:
  - mysql

git:
  depth: 3

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo 'memory_limit = 2048M' >> travis.php.ini;
  - phpenv config-add travis.php.ini
  - phpenv rehash

install:
  - travis_retry composer update --prefer-dist --no-suggest --ansi -o
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - app/console fos:user:create testUser info@mediaarea.net --env=test testPassword

script:
  - phpunit -c app
