language: php

php:
  - '5.6'
  - '7.0'

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - export SYMFONY_DEPRECATIONS_HELPER=weak

install:
  - composer --no-interaction --quiet install -o
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer update
    fi
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - app/console fos:user:create testUser info@mediaarea.net --env=test testPassword

script:
  - phpunit -c app
