easy_admin:
    site_name: 'MediaConchOnline'
    design:
        brand_color: '#3472A1'
        color_scheme: 'light'

    list:
        max_results: 20
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }

    entities:
        Users:
            class: AppBundle\Entity\User
            list:
                fields: ['username', 'email', 'firstname', 'lastname', 'enabled', 'lastLogin']
            form:
                fields:
                    - 'username'
                    - 'email'
                    - 'firstname'
                    - 'lastname'
                    - 'companyName'
                    - 'newsletter'
                    - { property: 'professional', type: 'AppBundle\Form\Type\ProfessionalType'}
                    - { property: 'country', type: 'AppBundle\Form\Type\CountryCustomType' }
                    - { property: 'language', type: 'AppBundle\Form\Type\LanguageCustomType' }
                    - 'enabled'
                    - 'roles'
            show:
                fields: ['username', 'email', 'firstname', 'lastname', 'companyName', 'newsletter', 'professional', 'country', 'language', 'enabled', 'lastLogin', 'roles']
            search:
                fields: ['username', 'email', 'firstname', 'lastname']
            disabled_actions: ['new']

        UserQuotas:
            class: AppBundle\Entity\UserQuotas
            list:
                fields: ['user', 'policies', 'uploads', 'uploadsTimestamp', 'urls', 'urlsTimestamp', 'policyChecks', 'policyChecksTimestamp']
            disabled_actions: ['new', 'edit', 'delete', 'show']

        UserQuotasDefault:
            class: AppBundle\Entity\UserQuotasDefault
            list:
                fields: ['user', 'policies', 'uploads', 'urls', 'policyChecks']
            new:
                fields: ['user', 'policies', 'uploads', 'urls', 'policyChecks']
            edit:
                fields: [{ property: 'user', type: 'AppBundle\Form\Type\EntityDisabledType'}, 'policies', 'uploads', 'urls', 'policyChecks']
            show:
                fields: ['user', 'policies', 'uploads', 'urls', 'policyChecks']
