imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']
    form_themes:
        - 'VichUploaderBundle:Form:fields.html.twig'
    globals:
        mco_ga_tracking: %mco_ga_tracking%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
      - AppBundle
    workers:
        cache_busting:
            enabled: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
            output: js/jquery.js
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
            output: js/bootstrap.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
            output: css/bootstrap.css
        jstree_js:
            inputs:
                - %kernel.root_dir%/../vendor/vakata/jstree/dist/jstree.min.js
            output: js/jstree.min.js
        jstree_css:
            inputs:
                - %kernel.root_dir%/../vendor/vakata/jstree/dist/themes/default/style.min.css
            output: css/jstree.min.css
        jstree_32px:
            inputs:
                - %kernel.root_dir%/../vendor/vakata/jstree/dist/themes/default/32px.png
            output: css/32px.png
        jstree_40px:
            inputs:
                - %kernel.root_dir%/../vendor/vakata/jstree/dist/themes/default/40px.png
            output: css/40px.png
        jstree_throbber:
            inputs:
                - %kernel.root_dir%/../vendor/vakata/jstree/dist/themes/default/throbber.gif
            output: css/throbber.gif
        select2_js:
            inputs:
                - %kernel.root_dir%/../vendor/ivaynberg/select2/dist/js/select2.full.min.js
            output: js/select2.js
        select2_css:
            inputs:
                - %kernel.root_dir%/../vendor/ivaynberg/select2/dist/css/select2.min.css
            output: css/select2.css

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    profile:
        form:
            type: mediaconch_user_profile
    registration:
        form:
            type: mediaconch_user_registration
        confirmation:
            enabled:    true
    from_email:
        address:        info@mediaarea.net
        sender_name:    MediaConchOnline
    service:
        mailer: mco.mailer.user

# VichUploader
vich_uploader:
    db_driver: orm
    mappings:
        xsl_policy:
            upload_destination: %kernel.root_dir%/../files/xsl_policy
            namer:              vich_uploader.namer_origname
            directory_namer:    mco.directory_namer.policy
        display:
            upload_destination: %kernel.root_dir%/../files/display
            namer:              vich_uploader.namer_origname
            directory_namer:    mco.directory_namer.policy

# FOSJsRoutingBundle
fos_js_routing:
    routes_to_expose:
        - app_checker_checkerajaxform
        - app_checker_checkerstatus
        - app_checker_checkerimplemstatus
        - app_checker_checkerreport
        - app_checker_checkerdownloadreport
        - app_checker_checkerpolicystatus
        - app_checker_checkerimplemandpolicystatus
        - app_checker_checkercreatepolicy
        - app_xslpolicy_xslpolicyrulefieldslist
        - app_xslpolicy_xslpolicyrulevalueslist
        - app_xslpolicy_xslpolicytree
        - app_xslpolicy_xslpolicytreedata
        - app_xslpolicy_xslpolicytreecreate
        - app_xslpolicy_xslpolicytreeimport
        - app_xslpolicy_xslpolicytreeexport
        - app_xslpolicy_xslpolicytreeedit
        - app_xslpolicy_xslpolicytreeduplicate
        - app_xslpolicy_xslpolicytreemove
        - app_xslpolicy_xslpolicytreedelete
        - app_xslpolicy_xslpolicytreerulecreate
        - app_xslpolicy_xslpolicytreeruleedit
        - app_xslpolicy_xslpolicytreeruledelete
        - app_xslpolicy_xslpolicytreeruleduplicate
        - app_xslpolicy_xslpolicytreerulemove

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

app:
    mediaconch:
        address: 127.0.0.1
        port: 4242
        api_version: 1.8
        absolute_url_for_mail:
            host: ~
            scheme: ~
            baseUrl: ~
