# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        # apply some configuration to these services
        public: true
        tags: ['controller.service_arguments']
